### PR TITLE
Update CAMARA_common.yaml

### PR DESCRIPTION
**Pull request by RubenBG7**
Little typos bugs fixed

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### What this PR does / why we need it: 

* correction
* bug

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

  Unavailable:
   description: Service Unavailable
   content:
    application/json:
     schema:
      $ref: "#/components/schemas/ErrorInfo"
     example:
      status: 503
      code: UNAVAILABLE
      message: Service Unavailable

AND

  Timeout:
   description: Timeout
   content:
    application/json:
     schema:
      $ref: "#/components/schemas/ErrorInfo"
     example:
      status: 504
      code: TIMEOUT
      message: Request timeout exceeded

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by patrice-conil — DISMISSED** [review]
/LGTM

**Review by jordonezlucena — APPROVED** [review]
/LGTM

**Review by jordonezlucena — APPROVED** [review]
/LGTM

**Review by PedroDiez — APPROVED** [review]
LGTM

**Review by rartych — APPROVED** [review]

**Pull request merged**
