### PR TITLE
Add `minItems: 1` & `maxItems: 1` for subscription `types`

### LINKED ISSUE #235: [Subscriptions-template]: Setting a `minItems: 1` for `types` in subscription-requests
**Problem description**
It's required to set the `types`-attribute in the subscription-request.
But it's not defined that minimum one item has to be set.
But without even one type a subscription does not make sense.

```yaml
    SubscriptionRequest:
      description: The request for creating a event-type event subscription
      type: object
      required:
        - sink
        - protocol
        - config
        - types
      properties:
       #...
        types:
          description: |
            Camara Event types eligible to be delivered by this subscription.
            Note: As of now we enforce to have only event type per subscription.
          type: array
          items:
            $ref: "#/components/schemas/SubscriptionEventType"
       #...
```
**Expected behavior**
```yaml
    SubscriptionRequest:
      description: The request for creating a event-type event subscription
      type: object
      required:
        - sink
        - protocol
        - config
        - types
      properties:
       #...
        types:
          description: |
            Camara Event types eligible to be delivered by this subscription.
            Note: As of now we enforce to have only event type per subscription.
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/SubscriptionEventType"
       #...
```

### PR DESCRIPTION
**Pull request by maxl2287**
#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:
Limits the minimum & maximum of requested `types` - list to one item.

#### Which issue(s) this PR fixes:

Fixes #235

### CODE REVIEW

**Review by PedroDiez — APPROVED** [review]
LGTM

**Review by patrice-conil — CHANGES_REQUESTED** [review]
Hi @maxl2287,
To ensure that we only have one item in the array, shouldn't we also set maxItems=1

**Comment by jlurien** [comment]
> Hi @maxl2287, To ensure that we only have one item in the array, shouldn't we also set maxItems=1

That is a discussion we are having for the Geofencing API, and there consensus is that it makes sense to add the maximum as well, for APIs aligned with this version of Commonalities. In future releases, if several events per subscription are allowed, we can remove the limit.

**Comment by maxl2287** [comment]
@jlurien @PedroDiez @patrice-conil:

I have now also set the `maxItems: 1`, so that we enforce _one_ subscription-type within a request at least for this upcoming meta-release `v0.4.0`.

**Comment by PedroDiez** [comment]
> @jlurien @PedroDiez @patrice-conil:
> 
> I have now also set the `maxItems: 1`, so that we enforce _one_ subscription-type within a request at least for this upcoming meta-release `v0.4.0`.

To me is fine if we have consensus on it @patrice-conil, @shilpa-padgaonkar, @rartych (giving LGTM in advance)

**Review by PedroDiez — APPROVED** [review]
LGTM

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Review by bigludo7 — APPROVED** [review]
LGTM

**Review by rartych — APPROVED** [review]

**Pull request merged**
