### PR TITLE
Mandate '+' in all phoneNumber formats

### LINKED ISSUE #87: Mandate '+' in all Phone Number formats
**Problem description**
The standards are a bit iffy around whether or not a '+' is required for phone numbers, we've agreed in SimSwap to have a '+' only, but I think it makes its sense to make it an agreed CAMARA standard across all APIs.

**Possible evolution**
https://github.com/camaraproject/NumberVerification/issues/65

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:
Update guidelines, common and glossary to mandate phone number '+' prefix in all formats

#### Which issue(s) this PR fixes:

Fixes #87

### CODE REVIEW

**Review by diegogonmar — APPROVED** [review]
LGTM

**Review by PedroDiez — APPROVED** [review]
LGTM

**Comment by fernandopradocabrillo** [comment]
hi @shilpa-padgaonkar , can you please review? thanks!

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM
@fernandopradocabrillo Ok from DT

**Pull request merged**
