### PR TITLE
Small typo fix to info.description template

### PR DESCRIPTION
**Pull request by eric-murray**
#### What type of PR is this?
* correction

#### What this PR does / why we need it:
Typo fix

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Special notes for reviewers:
None

#### Changelog input

```
 release-note
 - Typo fix in info.description template
```

#### Additional documentation 
None

### CODE REVIEW

**Review by PedroDiez — DISMISSED** [review]
LGTM

**Comment by rartych** [comment]
Another typo in line 2052: **Thee-** Legged...

**Review by rartych — APPROVED** [review]
LGTM

**Review by PedroDiez — APPROVED** [review]
LGTM

**Pull request merged**
