### PR TITLE
Replace broken links with relative links in API-linting-Implementation-Guideline.md

### PR DESCRIPTION
**Pull request by eric-murray**
#### What type of PR is this?
* documentation
* correction

#### What this PR does / why we need it:
Some links in API-linting-Implementation-Guideline.md are broken. This PR replaces all internal links in the document (broken or otherwise) with relative links.

#### Which issue(s) this PR fixes:
N/A

#### Special notes for reviewers:
None

#### Changelog input
```
 release-note
 - Replace broken links with relative links in API-linting-Implementation-Guideline.md
```

#### Additional documentation 
None

### CODE REVIEW

**Comment by hdamker** [comment]
Looks good to me. 

Just that instead of `../artifacts` also `/artifacts` works (and survive in case the API-linting-Implementation-Guideline would be moved into a sub directory of /documentation at some point).

**Comment by eric-murray** [comment]
You're right - it does work! This is obviously some "smart" implementation of relative links that my Unix experience has left me poorly prepared for. No doubt this is documented somewhere, but whilst I search for that, I updated the PR with the minimal relative links that still worked. Hopefully this document is now even more "future proof".

**Comment by hdamker** [comment]
> No doubt this is documented somewhere

Here: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links

**Review by PedroDiez — APPROVED** [review]
Minor suggestions

LGTM in advance

**Review by PedroDiez — APPROVED** [review]
LGTM

**Review by rartych — APPROVED** [review]

**Pull request merged**
