### PR TITLE
Security scheme in CAMARA_common.yaml

### LINKED ISSUE #217: Add security to CAMARA_common.yaml
**Problem description**
OpenAPI Specification allows APIs to describe their authentication and authorization requirements - their security requirements.
This is done by defining a [security scheme](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-scheme-object) that can than be [applied](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-requirement-object) to endpoints or to the API as a whole.

Commonly used security schemes of a Camara API should be in 
[CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml)

**Expected action**
The IdentityAndConsent WG developed one security scheme for OpenId Connect.

```yaml
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

This should be added to CAMARA_common.yaml and probably applied to the API as a whole.

### PR DESCRIPTION
**Pull request by rartych**
#### What type of PR is this?

* enhancement/feature

#### What this PR does / why we need it:
The IdentityAndConsent WG developed one security scheme for OpenId Connect.
Commonly used security schemes for Camara APIs is added to
[CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml)

#### Which issue(s) this PR fixes:

Fixes #217 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Changelog input

```
Security scheme for OpenId Connect added to CAMARA_common.yaml

```

### CODE REVIEW

**Review by jpengar — APPROVED** [review]
LGTM

**Review by eric-murray — APPROVED** [review]

**Review by PedroDiez — APPROVED** [review]
LGTM

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Review by patrice-conil — APPROVED** [review]
LGTM

**Pull request merged**
