### PR TITLE
Update API-design-guidelines - Issues 97&98

### LINKED ISSUE #97: Sorting & Filtering Optionality
**Problem description**
Design Guideline sections 8.2 Sorting and 8.3 Filtering doesn't state if these features must be supported or optional.

**Expected action**
Similar to section 8.1 Pagination, Design Guideline should state if Sorting and Filtering must be supported.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by rartych**
Updates in 8.Pagination, Sorting and Filtering

#### What type of PR is this?

Add one of the following kinds:

* correction

#### Which issue(s) this PR fixes:

Fixes #97 #98

#### Changelog input

```
 release-note

```

### CODE REVIEW

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Comment by shilpa-padgaonkar** [comment]
@gmuratk : Could you kindly review this PR for your raised issues 97 and 98?

**Comment by shilpa-padgaonkar** [comment]
@RubenBG7 @jordonezlucena : Could you kindly review this PR as code owners? Hopefully we can get this merged before the upcoming release.

**Review by gmuratk — APPROVED** [review]

**Review by RubenBG7 — COMMENTED** [review]
Of From TEF

**Review by jordonezlucena — APPROVED** [review]

**Pull request merged**
