### PR TITLE
Update UE-Identification.md

### PR DESCRIPTION
**Pull request by gmuratk**
Fixing issue with link to 3GPP TS 23.003

#### What type of PR is this?

Add one of the following kinds:

* correction

#### What this PR does / why we need it:

n/a

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:
quick fix to a broken link

#### Changelog input

```
 Link to 3GPP TS 23.003 fixed in UE-Identification.md

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by rartych — APPROVED** [review]
LGTM
Thanks for the correction!

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Review by jordonezlucena — APPROVED** [review]
LGTM

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Review by eric-murray — APPROVED** [review]

**Pull request merged**
