### PR TITLE
x-correlator_support_guidelines_in_notifications

### LINKED ISSUE #164: x-correlator in CloudsEvent notification?
**Problem description**
We took the decision to add `x-correlator` in our API which is fine but I have a doubt for notification.

Do we have to add the x-correlator as well in the POST {$request.body#/webhook/notificationUrl}? This is the notification send to the listener.

 In order to stay fully compliant with CloudsEvents (I did not find any mention x-correlator in CloudsEvents) I tend to think that we must not have this x-correlator in the notification response & endpoint (for CloudsEvent compliance and to get it easy for the developer)

**Expected behavior**

Add this specific comment in the guidelines

**Alternative solution**

**Additional context**

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

* enhancement
* documentation

#### What this PR does / why we need it:

Clarified the support of "X-Correlator" in notification flows. Documenting it in:
- API Design Guidelines
- Cloud Event Artifact

#### Which issue(s) this PR fixes:

Fixes #164 

#### Special notes for reviewers:

N/A

#### Changelog input

```
Clarified support of "X-Correlator" in notification flows

```

#### Additional documentation 

N/A

### CODE REVIEW

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Comment by bigludo7** [comment]
@rartych Probably this one can be merge wdyt?

**Comment by rartych** [comment]
Yes, even in [MoM](https://wiki.camaraproject.org/display/CAM/2024-04-15+Commonalities+WG+Minutes) there is decision to merge it.

**Pull request merged**
