### PR TITLE
Update and rename CAMARA_common.json to CAMARA_common.yaml

### LINKED ISSUE #106: Changes for Camara-common file in artifacts
**Problem description**

1. All our API specs across subprojects are contributed as yaml. Would propose changing https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.json to https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml keeping it consistent everywhere.

2. Would also propose making the file compliant to OAS and add a standard info object which would also solve camaraproject/ReleaseManagement#15 
image

3. Would extend its current content with https://github.com/camaraproject/Commonalities/issues/105 

**Expected behavior**

**Alternative solution**

**Additional context**

### PR DESCRIPTION
**Pull request by shilpa-padgaonkar**
#### What type of PR is this?

Add one of the following kinds:

* correction

#### What this PR does / why we need it:
changes json to yaml
extends file with device schema
conforms to oas

#### Which issue(s) this PR fixes:

Fixes camaraproject/Commonalities#106 camaraproject/ReleaseManagement#15 camaraproject/Commonalities#105 

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Comment by hdamker** [comment]
@jlurien @bigludo7 Would you have a view on the "extends file with device schema" part of this PR?

**Comment by rartych** [comment]
`CAMARA_common.json` is referenced in [section 7 of API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#7-common-data-types).
Beside the the change of the link the text of this section may need the update to indicate the target content and usage of  `CAMARA_common.yaml`.

**Comment by shilpa-padgaonkar** [comment]
@rartych : Could you please create a new issue for your point above?

**Comment by shilpa-padgaonkar** [comment]
@bigludo7  @jlurien : Could you kindly review as suggested in the comment above to ensure that the device schema is as needed?

**Review by bigludo7 — APPROVED** [review]
LGTM

**Review by RubenBG7 — APPROVED** [review]

**Comment by RubenBG7** [comment]
Ok from TEF side to PR 107 too

**Comment by rartych** [comment]
Merging as agreed.

**Pull request merged**
