### PR TITLE
Update CHANGELOG.md and README.md for release 0.2.0

### LINKED ISSUE #81: Commonalities release 0.2.0
**Problem description**
We have introduced changes to API Design Guidelines: mainly related to notifications in CloudEvents format, but also some other updates and corrections. Should we have the next release?

**Expected action**
Agree with TSC on Commonalities release schedule.

Define PRs and Issues that should be closed before the next release.

**Additional context**

### PR DESCRIPTION
**Pull request by rartych**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

CHANGELOG.md for v.0.2.0

#### Which issue(s) this PR fixes:

Fixes #81

#### Changelog input

```
CHANGELOG.md updated for v.0.2.0

```

### CODE REVIEW

**Review by eric-murray — APPROVED** [review]

**Comment by s68jk** [comment]
@rartych  The new file in artifacts is missing an entry the changelog https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml

**Comment by shilpa-padgaonkar** [comment]
@rartych The newly merged file https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml is missing an entry in changelog

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Review by shilpa-padgaonkar — APPROVED** [review]
/LGTM

**Pull request merged**
