### PR TITLE
Added filter criteria related Issue 103

### LINKED ISSUE #103: Operators gt, lt etc to enums too, that means that we are allowing to compare strings with lt, gt.... that not make sense
If we read the API guidelines designed, we are applying operators gt, lt etc to enums too, that means that we are allowing to compare strings with lt, gt.... that not make sense.

In adition we are not allowing with the actual guidelines to compare a value that is exactly that value , we have not defined the equals operator. Then my proposal is basing on the TMF 630 use:

image

For numeric and dates value allow:

.gt > / .gte >= / .lt < / .lte <= / .eq = / .neq !=

And for string enums:

.eq = / .neq !=

### PR DESCRIPTION
**Pull request by RubenBG7**
Updated desing guidelines related filtering discussed in issue 103

#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:

Upgrade Design guidelines

#### Which issue(s) this PR fixes:

Fixes #103

### CODE REVIEW

**Review by patrice-conil — APPROVED** [review]
/LGTM

**Review by jordonezlucena — DISMISSED** [review]
/LGTM

**Comment by rartych** [comment]
@gmuratk Thank you for spotting this. I have corrected the dates in the table to be compatible with date-time format.

**Review by rartych — APPROVED** [review]

**Review by patrice-conil — APPROVED** [review]
LGTM

**Comment by rartych** [comment]
Conflicts resolved with changes introduced in #123

**Review by rartych — APPROVED** [review]

**Pull request merged**
