### PR TITLE
Use ObjectName as discriminator's mapping key

### LINKED ISSUE #42: Usage of ClassName in Mappings section of discriminator
**Problem description**
As many Json frameworks use simple class names as JsonTypeName, we suggest adding a recommendation to use these class names as mapping keys. This will also serve as a workaround for openapi generators that do not properly handle the JsonTypeName of the derived class when the mappings section is present (this problem occurs on client side only) .

**Expected action**
New PR describing this recommandation

**Additional context**

### PR DESCRIPTION
**Pull request by patrice-conil**
#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:
Encourage usage of Object Name as discriminator's mapping key to facilitate usage of Json serializer/deserializer

#### Which issue(s) this PR fixes:

Fixes #42

#### Changelog input

```
Encourage usage of Object Name as discriminator's mapping key to facilitate usage of Json serializer/deserializer

```

### CODE REVIEW

**Comment by rartych** [comment]
I have modified the style of writing OpenAPI name to be aligned with other parts of the DG.

**Review by rartych — APPROVED** [review]
LGTM

**Review by eric-murray — APPROVED** [review]

**Review by rartych — APPROVED** [review]

**Comment by rartych** [comment]
@RubenBG7 @jordonezlucena  Could you review this PR? As it was discussed: it is recommendation to simplify life of developers using code generators.

**Comment by jordonezlucena** [comment]
lgtm

**Review by jordonezlucena — APPROVED** [review]

**Comment by rartych** [comment]
Merged as agreed in the call

**Pull request merged**
